name: Run tests through mvn test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: browser-actions/setup-chrome@v1
      - run: mvn test --file pom.xml
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-report
          path: target/cucumber-reports.html
          if-no-files-found: error